export enum AddressType {
  NONE = 'NONE',
  COMMUNITY_AUF = 'COMMUNITY_AUF',
  COMMUNITY_GMW = 'COMMUNITY_GMW',
  COMMUNITY_HUMAN = 'COMMUNITY_HUMAN',
  COMMUNITY_PROJECT = 'COMMUNITY_PROJECT',
  CRYPTO_ACCOUNT = 'CRYPTO_ACCOUNT',
  SUBACCOUNT = 'SUBACCOUNT',
  DEFERRED_TRANSFER = 'DEFERRED_TRANSFER',
}