export enum LedgerAnchorType {
  UNSPECIFIED = 'UNSPECIFIED',
  IOTA_MESSAGE_ID = 'IOTA_MESSAGE_ID',
  HIERO_TRANSACTION_ID = 'HIERO_TRANSACTION_ID',
  LEGACY_GRADIDO_DB_TRANSACTION_ID = 'LEGACY_GRADIDO_DB_TRANSACTION_ID',
  NODE_TRIGGER_TRANSACTION_ID = 'NODE_TRIGGER_TRANSACTION_ID',
  LEGACY_GRADIDO_DB_COMMUNITY_ID = 'LEGACY_GRADIDO_DB_COMMUNITY_ID',
  LEGACY_GRADIDO_DB_USER_ID = 'LEGACY_GRADIDO_DB_USER_ID',
  LEGACY_GRADIDO_DB_CONTRIBUTION_ID = 'LEGACY_GRADIDO_DB_CONTRIBUTION_ID',
  LEGACY_GRADIDO_DB_TRANSACTION_LINK_ID = 'LEGACY_GRADIDO_DB_TRANSACTION_LINK_ID',
}
